# Generated by Django 3.0 on 2025-02-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='USER',
        ),
    ]
