# Generated by Django 3.0 on 2025-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0004_auto_20250225_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loction',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='service_center',
            name='latitude',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_center',
            name='longitude',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
