# Generated by Django 3.0 on 2025-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0005_auto_20250225_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
