# Generated by Django 3.0 on 2025-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0006_auto_20250225_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_center',
            name='latitude',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='longitude',
            field=models.CharField(max_length=500),
        ),
    ]
